In [1]:
import numpy as np

## rand & randn & randint

### rand()

In [20]:
np.random.rand()

0.7617610599717616

In [27]:
np.random.rand(2,3)

array([[0.60463985, 0.70310861, 0.84110736],
       [0.70072553, 0.76399947, 0.07993689]])

### randn()

In [23]:
np.random.randn()

-1.2695093166510154

In [30]:
np.random.randn(3, 4)

array([[ 0.46542922, -1.99874494,  0.37887294,  0.15001865],
       [ 0.36491921,  1.59574384,  2.0121636 , -0.19030056],
       [-0.11468421,  0.21088641, -1.5108747 ,  0.80227685]])

In [43]:
np.random.randn(300, 400).mean()   # bu sıfıra yakın. parametleri ne kdar çoğaltırsan daha cok yaklaşır

-0.0005929695808443314

In [59]:
np.random.randn(300,400).std()    # bu 1 e yakın. parametreleri ne kadar çoğaltırsan daha çok yaklaşır

1.0017091532700675

### randint()

In [85]:
np.random.randint(10)

5

In [94]:
np.random.randint(4,10)

4

In [98]:
np.random.randint(1, 100, 8)   # 1 ile 100 arasında 100 dahil değil 8 tane sayı getirir. 1 vektördür...

array([96, 19, 21,  1, 70, 71, 83, 36])

In [23]:
np.random.randint(1, 100, size= (3,2))  # bu bir matrix dir

array([[58, 87],
       [49, 81],
       [67, 36]])

In [111]:
np.random.seed(48)
np.random.randint(1, 100, size= (3,2))   # seed belirlediğimiz için her seferinde aynı veriler gelir

array([[ 1, 52],
       [82, 69],
       [92, 49]])

## max & argmax & min & argmin

In [129]:

my_array_1 = np.random.randint(0, 50, 12)
my_array_1

array([29, 36, 26, 29, 23, 36, 29, 41, 30, 20, 16, 26])

In [130]:
my_array_1.min()  

16

In [131]:
my_array_1.argmin()   # en küçük değerin indexini verir...

10

In [132]:
my_array_1.max()

41

In [133]:
my_array_1.argmax()   # en büyük değerin indexini verir...

7

## size



In [134]:
my_array_1

array([29, 36, 26, 29, 23, 36, 29, 41, 30, 20, 16, 26])

In [138]:
aa = my_array_1.reshape(3, -1)
aa

array([[29, 36, 26, 29],
       [23, 36, 29, 41],
       [30, 20, 16, 26]])

In [139]:
aa.size   # toplam eleman sayısını verir...

12

In [141]:
aa.shape

(3, 4)

In [140]:
len(aa)    # satır sayısını döndürür...

3

## itemsize

In [142]:
aa

array([[29, 36, 26, 29],
       [23, 36, 29, 41],
       [30, 20, 16, 26]])

In [149]:
aa.itemsize   # her bir değerin boyutunu ifade eder. byte cinsinden gösterir...

4

In [43]:
aa.dtype

dtype('int32')

## copy()

In [146]:
my_array_2 = np.arange(1,17).reshape(-1,4)
my_array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [147]:
copyarr = my_array_2.copy()

In [148]:
copyarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
bb = my_array_2           # bu şekilde yaparsan eğer birbirlerinin değişikliği birbirini etkiler dedi hocamız. o yüzden copy daha saglıklı....

## transpose()

In [47]:
copyarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
copyarr.transpose()    # satırlar ve sütunlardaki değerleri değiştirir. Kalıcı değişiklik yapmaz....

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [53]:
copyarr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
copyarr.T  # kalıcı değişiklik yapmaz. Transpose bir diğer şekli T dir...

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

# Concatenation of the Arrays

In [55]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [56]:
y = np.arange(7,13)
y

array([ 7,  8,  9, 10, 11, 12])

In [59]:
xy = np.concatenate((x,y))   # tek boyutlu(vektör) array lerde yan yana ekleme yapar....
xy


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
xy = np.concatenate((x,y), axis= 0)
xy                                     # axis = 0 default değeridir. 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
xy = np.concatenate((x,y), axis= 1)    #  tek boyutlu array lerde axis = 1 kullanılamaz...
xy           

AxisError: axis 1 is out of bounds for array of dimension 1

In [152]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [153]:
b = np.array([[5,6], [7,8]])
b

array([[5, 6],
       [7, 8]])

In [155]:
c = np.concatenate((a,b))   # axis = 0 default degerinde alt alta ekleme yapar
c     

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [159]:
d = np.concatenate((a,b), axis= 1)   # default degerini axis = 1 olarak değiştirirsen yan yana ekleme yapar
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [66]:
e = np.array([[1,2], [3, 4]])
e

array([[1, 2],
       [3, 4]])

In [67]:
f = np.array([[5,6], [7,8], [9,10]])
f

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [69]:
ef = np.concatenate((e,f))    # sütun sayuları aynı satırları altına ekledi
ef

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [70]:
ef1 = np.concatenate((e,f), axis= 1)     # sütun sayıları farklı olduğu için yanına ekleyemedi. çünkü alttaki 9,10 fazlalık kaldı...
ef1  

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [71]:
np.concatenate((e,f), axis = None)    # none ifadesi elemanları birleştirir ve tek boyuta indirir..

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Splitting of the Arrays

In [161]:
my_array_3 = np.arange(1,9)
my_array_3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
np.split(my_array_3, 4)    # split tam bölünenlerde kullanılır

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [74]:
np.split(my_array_3, 5)   # tam bölünmediği için hata verdi

ValueError: array split does not result in an equal division

In [75]:
np.array_split(my_array_3, 6)    #aray_split ise tam sayı olmasa da böler...

[array([1, 2]), array([3, 4]), array([5]), array([6]), array([7]), array([8])]

In [167]:
np.split(my_array_3, [3])   #  4. indexe kadar olan sayıları aldı(4 dagil degil). O sayıdan sonrasını ayrı aldı...

[array([1, 2, 3]), array([4, 5, 6, 7, 8])]

In [169]:
aa = np.arange(1,18)
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [78]:
np.split(aa, [6])

[array([1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [171]:
np.split(aa, [6,8])   #bu şekilde de 3 e bölmüş oldu. 6. ve 8. indexleri dahil etmedi. burada 6 elemanı 5. index 8 eleamnı da 7. indextir...

[array([1, 2, 3, 4, 5, 6]),
 array([7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [80]:
my_array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [210]:
np.split(my_array_2, [1], axis= 0)   # axis = 0 default deger ve row ların indexlerinden bölmesi anlamına gelir


[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [176]:
np.split(my_array_2, [2], axis= 1)   # burada da sütunlardan böldü...

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

# Sorting of the Arrays

In [178]:
bb = np.array([2,4,1,5,3])
bb

array([2, 4, 1, 5, 3])

In [179]:
np.sort(bb)    # kalıcı değişiklik yapmaz

array([1, 2, 3, 4, 5])

In [180]:
bb

array([2, 4, 1, 5, 3])

In [181]:
bb.sort()

In [182]:
bb

array([1, 2, 3, 4, 5])

In [212]:
my_array_4 = np.random.randint(5, 50, size= (3,3))
my_array_4

array([[32, 14, 47],
       [29, 26, 46],
       [44, 19, 16]])

In [189]:
np.sort(my_array_4, axis= 0)   # 

array([[ 9, 11,  6],
       [21, 40, 24],
       [44, 40, 29]])

In [208]:
np.sort(my_array_4, axis=1)

array([[ 6,  9, 40],
       [29, 40, 44],
       [11, 21, 24]])

In [213]:
np.sort(my_array_4, axis = None) 

array([14, 16, 19, 26, 29, 32, 44, 46, 47])

## axis ile ilgili örnekler

In [214]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [215]:
arr1.ndim

1

In [216]:
arr2.ndim

1

In [217]:
arr1.shape

(3,)

In [218]:
arr2.shape

(3,)

In [219]:
my_array_4.shape

(3, 3)

In [220]:
my_array_4.size

9

In [221]:
my_array_4.itemsize

4

In [223]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [224]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])

In [225]:
arr3.ndim

2

In [226]:
arr4.ndim

2

In [227]:
arr3

array([[1, 2],
       [3, 4]])

In [229]:
arr4

array([[5, 6],
       [7, 8]])

In [235]:
np.concatenate((arr3,arr4), axis= 0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [236]:
np.concatenate((arr3,arr4), axis= 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])