In [1]:
import numpy as np

## ndim & ndmin

In [4]:
arr0 = np.array(5)     
arr0

array(5)

In [5]:
arr0.ndim

0

In [5]:
arr1 = np.array([1, 2])
arr1

array([1, 2])

In [6]:
arr1.ndim

1

In [6]:
my_list = list(range(0, 24))
print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


In [10]:
my_array = np.array(my_list)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
my_array.ndim

1

In [12]:
my_array.shape

(24,)

In [13]:
my_array1 = np.array(my_list, ndmin=2)
my_array1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
my_array1.ndim

2

In [16]:
my_array1.shape

(1, 24)

## dtype & astype()

In [17]:
my_int = np.array([1, 2, 3])
my_int

array([1, 2, 3])

In [18]:
my_int.dtype

dtype('int32')

In [19]:
my_int = np.array([1, 2, 3], dtype= "int64")
my_int

array([1, 2, 3], dtype=int64)

In [20]:
my_float = np.array([1, 2, 3.2, 4, 5])
my_float

array([1. , 2. , 3.2, 4. , 5. ])

In [21]:
my_float.dtype

dtype('float64')

In [23]:
my_string = np.array([1, 2, 3.2, 4, 5, "a"])
my_string

array(['1', '2', '3.2', '4', '5', 'a'], dtype='<U32')

In [24]:
my_string.dtype   # en fazla 32 karaktere sahip str dtype dır..

dtype('<U32')

In [26]:
my_float1 = np.array([1, 2, 3], dtype= "float")
my_float1

array([1., 2., 3.])

In [27]:
my_float1.dtype

dtype('float64')

In [29]:
my_float1.astype("int")

array([1, 2, 3])

In [30]:
my_float1.dtype   # eger degiskene atarsan o zaman kalıcı olur

dtype('float64')

In [31]:
new_int = my_float1.astype("int")   # eger degiskene atarsan o zaman kalıcı olur
new_int

array([1, 2, 3])

In [32]:
new_int.dtype

dtype('int32')

In [33]:
new_bool = my_float1.astype("bool")
new_bool 

array([ True,  True,  True])

## resize()

In [34]:
arr = np.array([[1, 3, 2], [4, 6, 5]])
arr

array([[1, 3, 2],
       [4, 6, 5]])

In [38]:
np.resize(arr, (2,2))

array([[1, 3],
       [2, 4]])

In [39]:
arr

array([[1, 3, 2],
       [4, 6, 5]])

In [40]:
np.resize(arr, (5, 2))

array([[1, 3],
       [2, 4],
       [6, 5],
       [1, 3],
       [2, 4]])

In [41]:
np.resize(arr, (7, 9))

array([[1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2]])

# Built in Methods

## arange()

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [45]:
np.arange(0, 10, 2.2)   # range fonksiyonundan farklı olarak float degerlerde de işlem yapabilirsin

array([0. , 2.2, 4.4, 6.6, 8.8])

In [46]:
np.arange(0, 10, -2.2)

array([], dtype=float64)

In [9]:
np.arange(10, 0, -2.2)

array([10. ,  7.8,  5.6,  3.4,  1.2])

## linspace()

In [48]:
np.linspace(1, 10, 4)   # 1 ve 10 dahil, birbirine eşit uzaklıkta 4 tane sayı getiriyor

array([ 1.,  4.,  7., 10.])

In [49]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
np.linspace(1, 20)   # default degeri 50 dir. 

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [51]:
np.linspace(1, 20, dtype= "int")   # çok kullanışlı olmadı burada ama yapabilirsin...

array([ 1,  1,  1,  2,  2,  2,  3,  3,  4,  4,  4,  5,  5,  6,  6,  6,  7,
        7,  7,  8,  8,  9,  9,  9, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13,
       14, 14, 14, 15, 15, 16, 16, 16, 17, 17, 18, 18, 18, 19, 19, 20])

In [55]:
np.linspace(1, 10, 4, endpoint= True)

array([ 1.,  4.,  7., 10.])

In [54]:
np.linspace(1, 10, 4, endpoint= False)    # default değeri endpoint = True, eğer bunu False yaparsan son sayıyı almaz...

array([1.  , 3.25, 5.5 , 7.75])

In [57]:
np.linspace(1, 10, 4, retstep= False)

array([ 1.,  4.,  7., 10.])

In [58]:
np.linspace(1, 10, 4, retstep= True)   # retstep default degeri False, eğer bunu True yaparsan kaçar arttığını da gösterir....

(array([ 1.,  4.,  7., 10.]), 3.0)

## logspace()

In [19]:
np.logspace(2, 3, num= 10)   # default değeri 10 yani 2 ^ 10 ve 3 ^ 10 arasında 5 tane sayı getirdi...

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

In [60]:
177.827941 - 100

77.82794100000001

In [61]:
316.22776602 - 177.827941  # linspace ile farklılığı sayıların arasındaki mesafenin aynı olmaması..

138.39982501999998

## zeros & zeros_like

In [63]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
arr2 = np.arange(1, 13).reshape(3, 4)

In [21]:

arr2

NameError: name 'arr2' is not defined

In [68]:
np.zeros_like(arr2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
np.zeros_like(arr2,dtype= bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## ones & ones_like

In [72]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [74]:
np.ones_like(arr2) * 4

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [75]:
np.ones_like(arr2) + 10

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

## eye()

In [76]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
np.eye(4, k=1 )

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [79]:
np.eye(4, k= -1 )

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## full & full_like


In [80]:
np.full((2, 5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [27]:
aa = np.full((2,5), np.nan)
aa

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [82]:
aa.dtype # içerisinde bir tane bile nan varsa type float olur

dtype('float64')