In [1]:
import numpy as np

# Bracket Indexing & Selection

In [2]:
arr1 = np.arange(12,21)
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr1[5]

17

In [4]:
arr1[-2]

19

In [5]:
arr1[1:4]

array([13, 14, 15])

In [6]:
arr1[::2]

array([12, 14, 16, 18, 20])

In [7]:
arr1[4:-1]

array([16, 17, 18, 19])

In [8]:
arr1[4:-1:-1]

array([], dtype=int32)

# Indexing a 2D Array (Matrices)

In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr_2d[2,1]

8

In [11]:
arr_2d[1::,1::]

array([[5, 6],
       [8, 9]])

# Slicing a 2D Array(Matrices)

In [12]:
arr2 = np.arange(0,36).reshape(6,-1)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [13]:
arr2[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [14]:
arr2[2:4,2:5]

array([[14, 15, 16],
       [20, 21, 22]])

In [15]:
arr2[2:5:2,:5:2]

array([[12, 14, 16],
       [24, 26, 28]])

# Fancy Indexing

In [16]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [17]:
arr2[(2,4,5),(0,2,4)]

array([12, 26, 34])

In [18]:
arr2[2:, (1,3,5)]

array([[13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [19]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [20]:
arr2[(1,3,5), 2:]


array([[ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [32, 33, 34, 35]])

## Selection on a Condition

In [21]:
np.random.seed(40)
arr3 = np.random.randint(1,50, size = (3,4))
arr3

array([[ 7, 28,  8, 38],
       [ 2, 13,  8, 20],
       [32, 11, 20, 28]])

In [22]:
arr3 > 20

array([[False,  True, False,  True],
       [False, False, False, False],
       [ True, False, False,  True]])

In [23]:
arr3[arr3 > 20]

array([28, 38, 32, 28])

In [24]:
arr4 = np.arange(1,51)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])